<div id="page">
    <p> Before anything else please ensure you have Node.js installed on this device. <br>
        If you have already installed it previously you can skip this step and move to the next phase of setup</p>
    <div class="row">
        <div class="column">
            <div class="download">

                <h2> Node.JS for Windows</h2>
                <a class="nav-link" href="https://nodejs.org/dist/v20.10.0/node-v20.10.0-x64.msi"> Download </a>

            </div>
        </div>
        <div class="column">
            <div class="download">

                <h2> Node.JS for Linux</h2>
                <a class="nav-link" href="https://nodejs.org/dist/v20.10.0/node-v20.10.0-linux-x64.tar.xz"> Download </a>

            </div>
        </div>
        <div class="column">
            <div class="download">

                <h2> Node.JS for Mac</h2>
                <a class="nav-link" href="https://nodejs.org/dist/v20.10.0/node-v20.10.0.pkg"> Download </a>

            </div>
        </div>

    </div>

    <p>Next you need to download the appropriate version of the program below <br>
        this will automate the installation of Cloud Carbon Footprint </p>
    <div class="row">

        <div class="column">
            <div class="download">

                <h2> Download For Windows </h2>

                <p> Click the button below to download and install</p>

                <a class="nav-link" href="testfile.bat" download="testfile.bat" id="fileRequest" onclick="document.getElementById('fileRequest').click()">Download</a>


            </div>
        </div>


        <div class="column">
            <div class="download">

                <h2> Download For Linux </h2>

                <p> Click the button below to download and install</p>


                <a class="nav-link" href="testfile.bat" download="testfile.bat" id="fileRequest" onclick="document.getElementById('fileRequest').click()">Download</a>

            </div>
        </div>


        <div class="column">
            <div class="download">

                <h2> Download For Mac </h2>

                <p> Click the button below to download and install</p>


                <a class="nav-link" href="testfile.bat" download="testfile.bat" id="fileRequest" onclick="document.getElementById('fileRequest').click()">Download</a>

            </div>
        </div>

    </div>


</div>