<div class="container-fluid" id="graphs">
    <!-- Content here -->

        <div>

             <button id="graph-button" onclick="changeChartData('us')">United-States</button>
             <button id="graph-button" onclick="changeChartData('eu')">Europe</button>
             <button id="graph-button" onclick="changeChartData('asia')">Asia</button>
             <button id="graph-button" onclick="changeChartData('ap')">Asia-Pacific</button>
             <button id="graph-button" onclick="changeChartData('')">All Servers</button>
        </div>

        <canvas id="test4"></canvas>
    </div>

    <script type="module" src="js/emissions3.js"></script>
</div>