<div class="container-fluid" id="graphs">
    <!-- Content here -->

    <div>
        <canvas id="test4"></canvas>
        <div>
            <button class="graph-button" onclick="toggleCountry('eu')">Toggle Europe</button>
            <button class="graph-button" onclick="toggleCountry('us')">Toggle US</button>
            <button class="graph-button" onclick="toggleCountry('asia')">Toggle Asia</button>
            <button class="graph-button" onclick="toggleCountry('ap')">Toggle AP</button>
            <!-- i believe in you <3 -->
        </div>
    </div>

    <script type="module" src="js/emissions4.js"></script>
</div>