<div class="container-fluid" id="graphs">
    <!-- Content here -->

    <div>

        <button id="graph-button" onclick="changeChartData('us')" tabindex="1">United-States</button>
        <button id="graph-button" onclick="changeChartData('eu')" tabindex="2">Europe</button>
        <button id="graph-button" onclick="changeChartData('asia')" tabindex="3">Asia</button>
        <button id="graph-button" onclick="changeChartData('ap')" tabindex="4">Asia-Pacific</button>
        <button id="graph-button" onclick="changeChartData('')" tabindex="5">All Servers</button>
    </div>

    <canvas id="test4"></canvas>
</div>

<script type="module" src="js/emissions3.js"></script>
</div>