<?php require_once('views/template/header.phtml')?>

<div class="container-fluid" id="graphs">
    <!-- Content here -->
    <div class="container-fluid"><canvas id="test3"></canvas></div>
    <div><canvas id="test4"></canvas></div>
    <div><canvas id="test5"></canvas></div>
    <script type="module" src="js/recommendations.js"></script>
    <script type="module" src="js/emissions.js"></script>
    <script type="module" src="js/footprint.js"></script>
</div>
</body>
</html>